sudo: required

dist: trusty

language: node_js

env:
  - CXX=g++-4.8

node_js:
  - "4.1"
  - "4.0"
  - "0.12"
  - "0.11"
  - "iojs"

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install software-properties-common -y -qq
  - sudo add-apt-repository -y ppa:ethereum/ethereum
  - sudo add-apt-repository -y ppa:ethereum/ethereum-dev
  - sudo apt-get update -qq
  - sudo apt-get install geth -y -qq
  - yes | geth --datadir ~/.ethereum-10101 &
  - sleep 5
  - killall geth
  - yes | geth --datadir ~/.ethereum-7 &
  - sleep 5
  - killall geth
