language: node_js

env:
  - CXX=g++-4.8

node_js:
  - "4.1"
  - "4.0"
  - "0.12"
  - "0.11"
  - "iojs"

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8

before_script:
  - npm install
  - npm install jshint

script:
  - ./runtests.sh
